const C={work:['登録なし','transparent'],off:['全休','#e0585f'],half:['半休','#ed8b3a'],paid:['有給','#3977d4'],paidHalf:['半給','#55b9d1'],maternity:['産休','#858a96'],childcare:['育休','#858a96'],celebration:['慶休','#858a96'],leave:['休職','#858a96'],care:['介休','#858a96']};
const people=[['社員A','営業部','2023/04/01',12,true],['社員B','営業部','2025/10/01',10,true],['社員C','設計部','2026/07/15',0,false],['社員D','総務部','2022/02/10',14,true],['社員E','企画部','2024/04/01',11,true],['社員F','工事部','2021/10/01',15,true],['社員G','デザイン部','2025/04/01',10,true]];
let requests=[{id:1,name:'社員B',dept:'営業部',code:'paid',start:'2026/08/18',end:'2026/08/18',reason:'私用',urgent:false,state:'部所長確認待ち'},{id:2,name:'社員C',dept:'設計部',code:'celebration',start:'2026/08/05',end:'2026/08/06',reason:'慶事のため',urgent:true,state:'総務確認待ち'},{id:3,name:'社員D',dept:'総務部',code:'care',start:'2026/08/24',end:'2026/08/26',reason:'家族の介護',urgent:false,state:'承認済み'}];
let role='employee',view='holiday',month=8,day=14,selectedCode='off',required=7.5;const pad=n=>String(n).padStart(2,'0'),key=(m,d)=>`2026/${pad(m)}/${pad(d)}`;
let holidays=JSON.parse(localStorage.getItem('shiftly-holidays-v2')||'{"2026/08/02":"off","2026/08/06":"half","2026/08/09":"off","2026/08/13":"paid","2026/08/17":"off","2026/08/21":"paidHalf","2026/08/24":"off","2026/08/28":"off"}');let overtime=JSON.parse(localStorage.getItem('shiftly-overtime-v2')||'[{"date":"2026/07/08","start":"18:00","end":"20:00","hours":2,"detail":"見積書作成"}]');
const menus={employee:[['holiday','休日登録'],['request','申請履歴'],['paid','有給管理'],['overtime','残業登録']],manager:[['approval','確認・承認'],['team','部署休日'],['otadmin','残業管理'],['alerts','有給アラート']],hr:[['overview','全社管理'],['final','最終確認'],['otadmin','残業管理'],['settings','クール設定'],['people','社員設定']]};
const head=(e,t,p)=>`<div class="head"><div><span class="eyebrow">${e}</span><h1>${t}</h1><p>${p}</p></div></div>`,state=s=>`<span class="pill ${s==='承認済み'?'done':s==='差戻し'?'returned':'pending'}">${s}</span>`,toast=s=>{let e=document.querySelector('#toast');e.textContent=s;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),1800)};
function setRole(r){role=r;view=menus[r][0][0];render()}function nav(){let n=document.querySelector('#nav');n.innerHTML=menus[role].map(([id,l])=>`<button data-v="${id}" class="${view===id?'on':''}">${l}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()})}
function cal(mode){let first=new Date(2026,month-1,1).getDay(),count=new Date(2026,month,0).getDate(),s='';for(let i=0;i<first;i++)s+='<div class="empty"></div>';for(let d=1;d<=count;d++){let info='';if(mode==='holiday'&&holidays[key(month,d)]){let c=C[holidays[key(month,d)]];info=`<em style="background:${c[1]}">${c[0]}</em>`}if(mode==='overtime'){let rs=overtime.filter(r=>r.date===key(month,d));if(rs.length)info=`<em style="background:#6252d7">${rs.reduce((n,r)=>n+r.hours,0)}時間</em><small>${rs[0].detail}</small>`}s+=`<button class="day ${day===d?'sel':''}" data-d="${d}"><span>${d}</span>${info}</button>`}return s}
const calendar=(mode)=>`<section class="card"><div class="cal-head"><button data-month="-1" ${month===6?'disabled':''}>‹</button><h2>2026年 ${month}月</h2><button data-month="1" ${month===9?'disabled':''}>›</button><div class="legend"><span><i style="background:var(--red)"></i>全休</span><span><i style="background:var(--orange)"></i>半休</span><span><i style="background:var(--blue)"></i>有給</span><span><i style="background:var(--cyan)"></i>半給</span><span><i style="background:var(--gray)"></i>特休等</span></div></div><div class="calendar"><div class="week">${['日','月','火','水','木','金','土'].map(x=>`<b>${x}</b>`).join('')}</div><div class="dates">${cal(mode)}</div></div></section>`;
function holiday(){let types=Object.entries(C).filter(([k])=>k!=='work').map(([k,v])=>`<button data-code="${k}" class="${selectedCode===k?'on':''}"><i class="dot" style="background:${v[1]}"></i>${v[0]}</button>`).join('');return head('HOLIDAY PLAN','休日登録','休日だけを登録します。空欄の日は通常出勤です。')+`<div class="summary"><div class="metric"><small>必要休日</small><b>${required}日</b></div><div class="metric"><small>取得予定</small><b>6.5日</b></div><div class="metric"><small>不足</small><b class="red">1日</b></div><div class="metric"><small>最大連続勤務</small><b>6日</b></div></div><div class="alerts"><div class="alert warning"><b>!</b><div><b>休日数が不足しています</b>必要休日数まであと1日です。</div></div><div class="alert danger"><b>×</b><div><b>休日予定を確定できません</b>7月28日〜8月2日が6連勤です。有給・半給・半休は連勤を中断しません。</div></div></div><div class="grid">${calendar('holiday')}<aside class="card editor"><small>選択中</small><h3>${month}月${day}日</h3><label>休日区分</label><div class="types">${types}<button data-code="work">登録取消</button></div><button id="saveHoliday" class="primary">変更を反映</button><button id="special" class="secondary" style="width:100%;margin-top:8px">特休を申請</button><p class="note">入力内容はこの端末内に保存されます。</p></aside></div>`}
function requestPage(){return head('REQUEST HISTORY','申請履歴','特休申請の進捗を確認します。')+table(['区分','期間','申請種別','状況'],requests.map(r=>[C[r.code][0],`${r.start}〜${r.end}`,r.urgent?'緊急':'通常',state(r.state)]))}
function paid(){return head('PAID LEAVE','有給管理','取得義務期間と予定を含めた取得状況です。')+`<div class="alerts"><div class="alert warning"><b>!</b><div><b>取得義務まであと1.5日</b>期限：2027年3月31日</div></div></div><div class="summary"><div class="metric"><small>年間付与</small><b>12日</b></div><div class="metric"><small>取得済み</small><b>2.5日</b></div><div class="metric"><small>取得予定</small><b>1.0日</b></div><div class="metric"><small>残日数</small><b>9.5日</b></div></div><div class="card privacy"><b>5日取得義務：対象</b><p>半給は0.5日として算入します。</p></div>`}
function overtimePage(){let times=Array.from({length:49},(_,i)=>{let m=540+i*15;return `${pad(Math.floor(m/60))}:${pad(m%60)}`}),total=overtime.filter(r=>r.date.slice(5,7)===pad(month)).reduce((n,r)=>n+r.hours,0);return head('OVERTIME ENTRY','残業登録','日付を選び、開始・終了時刻と内容を登録します。')+`<div class="grid">${calendar('overtime')}<aside class="card editor"><small>選択中</small><h3>${month}月${day}日</h3><label>開始・終了（15分刻み）</label><div class="time"><select id="start">${times.map(t=>`<option ${t==='18:00'?'selected':''}>${t}</option>`).join('')}</select><span>〜</span><select id="end">${times.map(t=>`<option ${t==='19:00'?'selected':''}>${t}</option>`).join('')}</select></div><label>業務内容</label><textarea id="detail"></textarea><button id="saveOt" class="primary">残業を登録</button><p class="note">${month}月合計 ${total}時間／45時間まで残り ${45-total}時間</p></aside></div>`}
function approvals(final=false){let target=final?'総務確認待ち':'部所長確認待ち',rs=requests.filter(r=>r.state===target);return head('APPROVAL INBOX',final?'最終確認':'確認・承認',final?'部所長確認済みの申請を総務が最終確認します。':'所属部署の申請を確認します。')+`<div class="summary"><div class="metric"><small>確認待ち</small><b>${rs.length}件</b></div><div class="metric"><small>緊急</small><b class="red">${rs.filter(r=>r.urgent).length}件</b></div><div class="metric"><small>本日処理済み</small><b>4件</b></div></div>`+(rs.map(r=>`<article class="card approval"><div class="person"><span class="avatar">${r.name.slice(-1)}</span><div><b>${r.name}</b><small>${r.dept}</small></div><span class="pill pending code">${C[r.code][0]}</span></div><div class="detail"><span>期間<br><b>${r.start}〜${r.end}</b></span><span>理由<br><b>${r.reason}</b></span><span>状態<br><b>${r.state}</b></span></div><div class="actions"><button class="secondary" data-action="return" data-id="${r.id}">差戻し</button><button class="primary" data-action="approve" data-id="${r.id}">${final?'最終承認':'確認する'}</button></div></article>`).join('')||'<div class="card privacy">確認待ちはありません。</div>')}
function team(){return head('DEPARTMENT HOLIDAY','部署休日','営業部の休日登録と連続勤務を確認します。')+table(['社員','休日予定','必要休日','最大連続勤務','状態'],[['社員A','6日','7.5日','6日','<span class="pill returned">確定不可</span>'],['社員B','7.5日','7.5日','5日','<span class="pill done">適合</span>']])}
function paidAlerts(){return head('PAID LEAVE ALERTS','有給アラート','期限前月の通知対象です。')+`<div class="alert warning"><b>!</b><div><b>1名が取得不足見込みです</b>予定を含めても法定5日に届きません。</div></div>`+table(['社員','期限','取得済＋予定','不足','通知'],[['社員B','2026/08/31','4.5日','0.5日','<span class="pill pending">通知済み</span>']])}
function otAdmin(){let rows=people.map((p,i)=>[p[0],p[1],`${[28,17.5,12,4,31,22,9][i]}時間`,'45時間',`<div class="progress"><i style="width:${[62,39,27,9,69,49,20][i]}%"></i></div>`,[28,17.5,12,4,31,22,9][i]>=30?'<span class="pill pending">注意</span>':'<span class="pill done">適正</span>']);return head('OVERTIME CONTROL',role==='manager'?'部署の残業管理':'全社残業管理','月間残業時間と法定残業可能時間を確認します。')+`<div class="alerts"><div class="alert info"><b>i</b><div><b>30時間以上：1名</b>45時間までの残りを確認してください。</div></div></div>`+table(['社員','部署','月間残業','法定残業可能時間','使用率','状態'],role==='manager'?rows.slice(0,2):rows)}
function overview(){return head('COMPANY OVERVIEW','全社管理','休日登録、申請、有給取得状況を横断確認します。')+`<div class="summary"><div class="metric"><small>対象社員</small><b>48名</b></div><div class="metric"><small>休日不足</small><b class="red">6名</b></div><div class="metric"><small>6連勤違反</small><b class="red">2名</b></div><div class="metric"><small>有給不足見込み</small><b class="amber">1名</b></div></div><div class="cards"><section class="card panel"><h3>部署別休日登録</h3>${['営業部 12/14','総務部 7/8','企画部 5/8','設計部 9/10','工事部 10/12','デザイン部 6/6'].map(x=>`<p>${x}</p>`).join('')}</section><section class="card panel"><h3>申請状況</h3>${requests.map(r=>`<p><b>${r.name}・${C[r.code][0]}</b><br><small>${r.dept}　${r.state}</small></p>`).join('')}</section></div>`}
function settings(){return head('COURSE SETTINGS','クール設定','全社員共通の必要休日日数を設定します。')+`<section class="card settings"><div class="setting"><div><b>2026年度・第3クール</b><p>2026年6月21日〜9月20日</p></div><label>必要休日日数 <input id="required" type="number" step="0.5" value="${required}"></label></div><p>中途入社・退職：在籍日数で自動按分</p><p>長期休業：対象期間を除外して按分</p><p>端数処理：0.5日単位で四捨五入</p><button id="saveSettings" class="primary">設定を保存</button></section>`}
function peoplePage(){return head('EMPLOYEE SETTINGS','社員設定','在籍期間、有給基準日、年間付与日数を管理します。')+table(['社員','部署','入社日','年間付与','5日義務'],people.map(p=>[p[0],p[1],p[2],`${p[3]}日`,p[4]?'<span class="pill pending">対象</span>':'<span class="pill done">対象外</span>']))+`<div class="card privacy">社員は本人のみ、部所長は所属部署のみ、総務は全社員を閲覧できます。</div>`}
function table(h,rows){return `<section class="card table-card"><table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`}
function modal(){let box=document.createElement('div');box.className='toast';box.style.cssText='inset:15%;transform:none;left:15%;bottom:auto;background:white;color:var(--ink);padding:25px;border:1px solid var(--line)';box.innerHTML=`<b>特休を申請</b><p>区分：有給／半給／産休／育休／慶休／休職／介休</p><button class="primary">申請する</button> <button class="secondary">閉じる</button>`;document.body.append(box);box.querySelector('.secondary').onclick=()=>box.remove();box.querySelector('.primary').onclick=()=>{requests.unshift({id:Date.now(),name:'社員A',dept:'営業部',code:'paid',start:'2026/08/22',end:'2026/08/22',reason:'私用',urgent:false,state:'部所長確認待ち'});box.remove();toast('特休申請を送信しました')}}
function bind(){document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{day=+b.dataset.d;render()});document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month+=+b.dataset.month;day=1;render()});document.querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>{selectedCode=b.dataset.code;document.querySelectorAll('[data-code]').forEach(x=>x.classList.toggle('on',x===b))});let x=document.querySelector('#saveHoliday');if(x)x.onclick=()=>{if(selectedCode==='work')delete holidays[key(month,day)];else holidays[key(month,day)]=selectedCode;localStorage.setItem('shiftly-holidays-v2',JSON.stringify(holidays));toast('休日区分を更新しました');render()};x=document.querySelector('#special');if(x)x.onclick=modal;x=document.querySelector('#saveOt');if(x)x.onclick=()=>{let s=document.querySelector('#start').value,e=document.querySelector('#end').value,d=document.querySelector('#detail').value.trim(),mins=t=>+t.slice(0,2)*60+ +t.slice(3);if(!d||mins(e)<=mins(s)){toast('時刻と内容を確認してください');return}overtime.unshift({date:key(month,day),start:s,end:e,hours:(mins(e)-mins(s))/60,detail:d});localStorage.setItem('shiftly-overtime-v2',JSON.stringify(overtime));toast('残業を登録しました');render()};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let r=requests.find(x=>x.id==b.dataset.id);r.state=b.dataset.action==='return'?'差戻し':r.state==='部所長確認待ち'?'総務確認待ち':'承認済み';toast('申請を更新しました');render()});x=document.querySelector('#saveSettings');if(x)x.onclick=()=>{required=+document.querySelector('#required').value;toast('設定を保存しました')}}
function render(){nav();let f={holiday,request:requestPage,paid,overtime:overtimePage,approval:()=>approvals(false),team,otadmin:otAdmin,alerts:paidAlerts,overview,final:()=>approvals(true),settings,people:peoplePage}[view];document.querySelector('#app').innerHTML=`<section class="page">${f()}</section>`;bind()}
document.querySelector('#role').onchange=e=>setRole(e.target.value);let prompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;document.querySelector('#install').classList.remove('hidden')});document.querySelector('#install').onclick=async()=>{if(prompt){prompt.prompt();await prompt.userChoice}};if('serviceWorker'in navigator){let reload=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reload){reload=true;location.reload()}});navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update())}render();
